---
title: SE project Edmonds Data exploration and question
author: "Darius McDaniel"
date: "November 11, 2015"
output: html_document
---

----------

## This document will aim to answer different questions from the edmonds data. There will be a question answered for most of the main topics covered in this semesters class.

+ 1. All programs will be added and commited to git.
+ 2. Questions 
    Q1. Dplyr.
        
       Based on the visitor data how long did the visits last and did the longer visit times lead to purchases or vis versa?
        
        
         Q2. Visualizations (ggplot2, googlevis, cardodb, google fusion tables)
        
       Using zipcodes provided from transactions map the US top five models bought? Look at this per year bought?
       Compare the graphs for the visits less than an hour that purchased cars to the 1-5hr visits?
       Are there differences?
      
        
    Q3. JSON/XML
    
        Create a data frame based on top models bought in each year and pull               important consummer data?
      
    Q4. SQL (sqldf or Rsqlite)
        Create a RSQL database and figure out how many purchases where classified as Trucks, SUVs and cars , and the popular years for makers? 

    Q5. ObjectS
    Create a print for the top vehicles,
        plot the top purchased and give a summary of  top visited and top purchased. 
        All this from an object for this data.


##Plan to work on one piece a day starting Monday November 16th.


##Note to self place data for questions outside of SQL in fread
##     fread("data.csv", stringsAsFactor=FALSE)

